### ISSUE TITLE
Download broken due to deprecated API response

### ISSUE THREAD

**Issue by ivabrajer** [dawidd6/action-download-artifact#10]
I'm trying to use latest release version (v2.5.0) in order to retrieve artifacts that were previously build with `build_artifacts.yml` workflow. I can see them and are able to download them manually so I'm sure that `artifacts-v1.2.0` exist before running this workflow.

```
name: Testing my workflow

on:
  push:
    branches:
      - my-feature-branch

jobs:
  test:

    runs-on: ubuntu-18.04
    
    steps:
    - name: Checkout git repository
      uses: actions/checkout@v2

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2.5.0
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: build_artifacts.yml
        name: artifacts-v1.2.0
        path: artifacts/bin
```

However, instead of downloading requested artifacts I get the following error response from Github:

```
2020-05-06T15:37:33.1706727Z ==> Commit: 
2020-05-06T15:37:34.4553787Z [@octokit/paginate-rest] "response.data.workflow_runs" is deprecated for "GET /repos/******/actions/workflows/build_artifacts.yml/runs". Get the results directly from "response.data"
2020-05-06T15:37:37.1867481Z ##[error]Cannot read property 'id' of undefined
```

Also tried to do the following but none of it didn't help either:
* running this workflow on one of self-hosted runners
* changing action version from `v2.5.0` to `v2`
* removing `github_token` parameter

Am I missing something here or is that something that needs to be resolved by changing how response is parsed? Thanks in advance!
