### ISSUE TITLE
no matching workflow run found

### ISSUE THREAD

**Issue by crakmartin** [dawidd6/action-download-artifact#102]
Hi, I need help figuring out why I got "no matching workflow run found". I did experiments with this action, in a personal repo, and I got succes. When I integrate this action in my corpo repo, I got the error "no matching workflow run found".

I really triple check if the name of the given workflow parameter is good. I copy/paste it to make sure it is spell correctly.

I've read the code, but can't figure out what's happening.

Kind regards
Martin

```
      - name: Download backend artifact
        uses: dawidd6/action-download-artifact@v2.14.1
        continue-on-error: true
        with:
          workflow: jerkmate-backend.yml
          workflow_conclusion: success
          commit: ${{ github.sha }}
          name: docker_images
          path: ./jerkmate-backend/docker_images
```
