### ISSUE TITLE
Unexpected input(s) 'check_artifacts'

### ISSUE THREAD

**Issue by jmcdo29** [dawidd6/action-download-artifact#113]
When adding the `check_inputs` to the workflow, GitHub Actions reports a warning

```
Warning: Unexpected input(s) 'check_artifacts', valid inputs are ['github_token', 'workflow', 'workflow_conclusion', 'repo', 'pr', 'commit', 'branch', 'event', 'run_id', 'run_number', 'name', 'path']
```

It looks like maybe just a new release needs to be made, as the last one was August 4 and this feature was added in August 11?

Here's a snippet of the workflow

```yml
    steps:
      - uses: actions/checkout@v2
      - name: Download Server Coverage
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: monorepo.yml
          workflow_conclusion: success
          branch: master
          check_artifacts: true
          name: server-coverage
          path: coverage/server

      - name: Download Web App Coverage
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: monorepo.yml
          workflow_conclusion: success
          branch: master
          check_artifacts: true
          name: web-app-coverage
          path: coverage/web-app
```
