### ISSUE TITLE
Help on usage

### ISSUE THREAD

**Issue by hiren929** [dawidd6/action-download-artifact#123]
I need some help on usage of this action. Is following case is supported?

There are two workflows in the project: build workflow and deploy workflow. 

build workflow gets triggered upon pull request creation to master branch 
deploy workflow gets triggred upon merge of the PR to the master branch

build workflow uploads an artifact that deploy workflow downloads using this action.

download workflow has this code:
```
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build-workflow.yml
          workflow_conclusion: success
          commit: ${{github.event.pull_request.head.sha}}
          name: app-artifact
          path: ./
```

If two pull requests are created few minutes apart, two build workflows kicks off and uploads two different artifacts.

PR1 -> build workflow runs -> uploads artifact1
some time later....
PR2 -> build workflow runs -> uploads artifact2

Note that PR1 is create earlier than PR2. artifact2 is associated with the last run of the build workflow.

when PR1 is merged, deploy workflow runs and it should download artifact1 using code above, but instead it incorrectly downloads artifact2, as it is associated with the last run of the build workflow. 

I have tried both commit and pr inputs of the action without success. 
commit: ${{github.event.pull_request.head.sha}}
pr: ${{github.event.pull_request.number}}

It always downloads artifact associated with last run.

How is pr: ${{github.event.pull_request.number}} supposed to function?

Thanks in advance

**Comment by dawidd6** [comment]
I would like to see whole workflows or at least triggers of each one.

**Comment by hiren929** [comment]
**build workflow that runs upon PR creation to master branch:**

branch-1 code that uploads artifact1.txt 

```
name: Build And Deploy To Dev
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:    

jobs: 
  build-app: 
    runs-on: custom-runner
    env:
      Verbosity: Normal
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Upload a Build Artifact
        id: upload_build_artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app-artifact
          path: |            
            ./artifact1.txt
```


branch-2 code that uploads artifact2.txt 

```
name: Build And Deploy To Dev
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
  workflow_dispatch:    

jobs: 
  build-app: 
    runs-on: custom-runner
    env:
      Verbosity: Normal
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Upload a Build Artifact
        id: upload_build_artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: app-artifact
          path: |            
            ./artifact2.txt
```

Deploy workflow that runs upon PR merge:

```
name: Deploy To Prod
on:
  push:
    branches:
      - master
  workflow_dispatch:    

jobs:
  deploy-to-prod:
    runs-on: custom-runner
    environment: 'prod-next'
    env:
      Verbosity: Normal
    steps:      
      - name: Download Build Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: dev-build-and-deploy.yml
          workflow_conclusion: success
          #commit: ${{github.event.pull_request.head.sha}}
          pr: ${{github.event.pull_request.number}}
          name: app-artifact
          path: ./
```
