### ISSUE TITLE
Reading error message

### ISSUE THREAD

**Issue by AbiCS26** [dawidd6/action-download-artifact#128]
In my workflow, I have to download the artifact from the previous run and upload the updated artifact. This uploading action is based on the outcome of action-download, if downloading fails I won't upload any artifact because I don't want to override the existing data with a new one.
So, for the first run, of-course download action is gonna fail because there won't be any artifacts but, I want to upload the new artifact.

Is there any way to differentiate and read or access the error message ("no artifacts found" or any API error)?
So that I can perform the next action accordingly.

**Comment by dawidd6** [comment]
Run upload only when download fails. GitHub Actions provides tools for that.

**Comment by AbiCS26** [comment]
I want to upload only for the first run fail ("no artifacts found"). Later on, if there is a failure in download action I don't want to upload anything.

**Comment by jamesmortensen** [comment]
Hi @dawidd6 I can explain what @AbiCS26 is looking for.  The problem we're facing is that there are two cases where we're not able to download artifacts:

1.  The artifact is not found, OR
2.  We have exceeded our X API requests per hour and the artifact is present but cannot be downloaded due to our action not being able to access the GitHub API.  

In the case where we exceed the API threshold, we don't want to assume no data and overwrite what is already present because when we download an artifact, we're updating the data and re-uploading it again.

In the source code, we can see that this action is setting the error message in `core.setFailed(error.message)`, but from looking at the `@actions/core` codebase, it looks like this only prints the error message to the logs and does not make it available as a variable that we can query and use in our code.  

https://github.com/dawidd6/action-download-artifact/blob/09385b76de790122f4da9c82b17bccf858b9557c/main.js#L159

What we're trying to do is something like in this simplified example:

```
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - id: simple-download-example
        uses: dawidd6/action-download-artifact@v2
        with:
            workflow:  sample.yaml
            name: artifact_to_be_updated
            search_artifacts: true

      - id: next_step
        name: Why did it fail
        run: |
          if [[ ${{ steps.simple-download-example.outputs.error_message }} == "API rate limit exceeded for installation ID xxxxxxx" ]]; then 
               # do one thing here
          elif [[ ${{ steps.simple-download-example.outputs.error_message }} == "no matching workflow run found" ]]; then 
               # do something completely different here
          fi
```

If we were running a command directly in the shell instead of using an action, we would simply try/catch everything and then add the error message as an output variable like so and then use that output variable later:

```
    echo "::set-output name=error_message::API rate limit exceeded for installation ID xxxxxxx"
```

Then later:

```
    echo "${{ steps.simple-download-example.outputs.error_message }}"
```

Currently, we are able to access whether the download artifact action was success, failed, completed, etc, but what we're looking for is the reason for the failure.  Hope this helps clarify!  

James
