### ISSUE TITLE
dawidd6/action-download-artifact@v2.16.0 with commid Id fails with "Error: no artifacts found"

### ISSUE THREAD

**Issue by shankarseal** [dawidd6/action-download-artifact#130]
Upload workflow (build.yml):

```
name: MSBuild

on: pull_request

jobs:
  build:
    strategy:
      matrix:
        configurations: [Debug, Release]
        ...
    steps:
    - name: Upload Build Output
      uses: actions/upload-artifact@v2.2.4
      with:
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
        retention-days: 5
```

Download worfklow:
```
name: Kernel_Test_VM

on: pull_request

jobs:
  run_tests:
    strategy:
      matrix:
        configurations: [Debug, Release]
        ...
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
        timeoutSeconds: 1500
        intervalSeconds: 15
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: build (${{env.BUILD_CONFIGURATION}})
        ref: ${{ github.event.pull_request.head.sha || github.sha }}

    - name: Download build artifact
      uses: dawidd6/action-download-artifact@v2.16.0
      with:
        # Required, workflow file name or ID
        workflow: build.yml
        workflow_conclusion: ""
        commit: ${{ github.event.pull_request.head.sha || github.sha }}
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}

```

Workflow result:

```
Run fountainhead/action-wait-for-check@v1.0.0
...
Retrieved 1 check runs named build (Debug)
Found a completed check with id 4975074926 and conclusion success


Run dawidd6/action-download-artifact@v2.16.0
  with:
    workflow: build.yml
    commit: cb3a09da46211cc5ec72514ab5b2b91b4f287618
    name: Build x64 Debug
    path: C:\actions_runner\_work\ebpf-for-windows\ebpf-for-windows/x64/Debug
    github_token: ***
    repo: microsoft/ebpf-for-windows
  env:
    BUILD_CONFIGURATION: Debug
    BUILD_PLATFORM: x64
==> Workflow: build.yml
==> Repo: microsoft/ebpf-for-windows
==> Conclusion: 
==> Commit: cb3a09da46211cc5ec72514ab5b2b91b4f287618
==> RunID: 1759372979
Error: no artifacts found
```

The commit Id and Run ID looks good - I double checked from Actions menu of the repo. However the WF always fails with `Error: no artifacts found`.

If I remove the `commit:` parameter then the WF succeeds. However, since there can be multiple PRs and multiple WFs running simultaneously, for the correct solution, I have to pass the commit Id.

I tried with PR as well, same issue.

Maybe specifying the `run_id`  parameter would work, but unfortunately, I dont know how I can find the run Id of the `build.yml` workflow for a given commit or PR.

**Comment by dawidd6** [comment]
Try to wait some more time between uploading and downloading. GitHub API could be slow some times.

**Comment by shankarseal** [comment]
I tried putting a 1 minute sleep after upload completed. Still same result.

**Comment by ashishmg-gds** [comment]
@dawidd6 Im also facing the same issue in my PRs. This only started like from last week i guess. because last week my workflows were running fine

**Comment by ThePieMonster** [comment]
Is this project dead? Are the workflows still working?

**Comment by dawidd6** [comment]
Not dead. The action is working, I just don't know what could be wrong here.

**Comment by re1ro** [comment]
@shankarseal @ashishmg-gds @ThePieMonster @dawidd6 
Hey there! I had the similar issue with not finding the artifact by the name. I had to add
`search_artifacts: true` to the configuration so it will look into previous builds to match the commit and artifact name

Example:
```
- name: Download build artifact
      uses: dawidd6/action-download-artifact@v2.16.0
      with:
        # Required, workflow file name or ID
        workflow: build.yml
        commit: ${{ github.event.pull_request.head.sha || github.sha }}
        name: Build x64 ${{ matrix.configurations }}
        path: ${{ github.workspace }}/${{env.BUILD_PLATFORM}}/${{env.BUILD_CONFIGURATION}}
        search_artifacts: true
```

**Comment by jbkoh** [comment]
Not sure exactly related to this one, but I had a similar issue but it only happened after upgrading [upload-artifact](https://github.com/actions/upload-artifact) from v2 to v3. I didn't fully investigate the change, so not entirely sure.

I have a workflow (W_A) using this download action to download an artifact from another workflow (W_B) uploaded by upload-artifact above. W_A downloads based on the branch name so if W_B uploads the artifact within the same branch, W_A can pick an artifact from the latest build of that branch.

But after upgrading upload-artifact v2 to v3, W_A cannot pick the latest build from W_B but only the older one uploaded by upload-artifact v2. 

I resolved the issue by downgrading the upload-artifact version to v2, but figured that experience may give some hint to what's happening here...

Thanks for the great project btw.

**Comment by dawidd6** [comment]
I just switched to upload-artifact@v3 and my CI workflows are working just fine.

**Comment by jbkoh** [comment]
Got it. I will have to look into my workflow again then. Thanks!

**Comment by sunnyoswalcro** [comment]
it works for me in 1 repo and doesn't work in another.

Both workflows using:
```
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: XXXX
          workflow: terraform.yml
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}

```

Working Logs
```
==> Workflow: terraform.yml
==> Repo: XXX
==> Conclusion: success
==> RunID: XXXX
==> Artifact: XXX
==> Downloading: tfplan.zip (7 B)
  inflating: tfplan/world.txt

```


Non-Working Logs:
```
==> Workflow: terraform.yml
==> Repo: XXX
==> Conclusion: success
==> PR: 42
==> Commit: XXX
```
