### ISSUE TITLE
[@octokit/paginate-rest] "response.data.workflow_runs" is deprecated

### ISSUE THREAD

**Issue by otreblan** [dawidd6/action-download-artifact#14]
![Screenshot_2020-06-02 2020-01-est-19 proyecto](https://user-images.githubusercontent.com/39320840/83537311-013f0100-a4ba-11ea-807a-c2b8939559ad.png)

https://github.com/2020-01-est-19/proyecto/runs/731399431

I'm trying to download an artifact from the same commit from my [R CI](https://github.com/2020-01-est-19/proyecto/blob/master/.github/workflows/r.yml) workflow
```yml
    - uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: r.yml
        name: proyecto
        commit: ${{github.event.push.head.sha}}
```
