### ISSUE TITLE
Error: no matching workflow run found

### ISSUE THREAD

**Issue by ashishmg-gds** [dawidd6/action-download-artifact#147]
Everything was workign fine till last 2 hours.  

I just provide the `pr` in the arguments

```
- uses: dawidd6/action-download-artifact@v2
   with:
       pr: ${{github.event.pull_request.number}}
        workflow: ci.yml
```

Log:

```
==> Workflow: ci.yml
==> Repo: xxxxxxxxx
==> Conclusion: success
==> PR: 304
==> Commit: 01xxx963c6xxxb0b6exxxx58113513927xxx

```
 Its not able to get `RunID` i think

**Comment by juliandittmann** [comment]
Hi, 

i have the same problem. 

I guess the RunIDs after 2147483647 are the problem.

Last Run before 2147483647 worked for me: 
![image](https://user-images.githubusercontent.com/50719320/162735236-334746e5-43b6-4635-a561-9251908c667c.png)

**Comment by aleksandar-embroker** [comment]
+ 1 For the same issue to bring this to antention

**Comment by jenn4** [comment]
+1 having same issue too

**Comment by flsusp** [comment]
+1 the same here

**Comment by mattias-de-coninck-ad** [comment]
+ 1 same here

**Comment by SHancockQ** [comment]
+1 Same here

**Comment by darianstlex** [comment]
+1 same

**Comment by aleksandar-embroker** [comment]
> 2147483647
https://en.wikipedia.org/wiki/2,147,483,647 coincidence or some Java API endpoint bug on GitHub side?

**Comment by aleksandar-embroker** [comment]
> Hi,
> 
> same problem here.
> 
> I guess RunIDs after 2147483647 are causing this.
> 
> Last Run before 2147483647 worked for me: ![image](https://user-images.githubusercontent.com/50719320/162735236-334746e5-43b6-4635-a561-9251908c667c.png)

https://en.wikipedia.org/wiki/2,147,483,647 coincidence or some Java API endpoint bug on GitHub side?

**Comment by flsusp** [comment]
This is the `Integer.MAX_VALUE` in Java...

**Comment by MarcoAStake** [comment]
How can reset RUNID?

**Comment by dsun-cp** [comment]
Is this an issue with the github actions REST API or this action here?
And any update on this?

**Comment by lele0108** [comment]
Folks -- until this is fixed you can use the `run_id` directly and the artifact will be found

**Comment by alexeh** [comment]
> Folks -- until this is fixed you can use the `run_id` directly and the artifact will be found

Same issue here.  @lele0108 any example on how set `run_id`?

**Comment by Layoric** [comment]
@alexeh if you use `workflow_conclusion` you will have to replace with `run_id` plus the value of the upload artifact.

Eg

```yaml
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: upload_workflow.yml
        run_id: 2152869823
        # workflow_conclusion: success
        name: Name
        commit: ${{ github.sha }}
        path: ./build/staging
```

You can find the run ID by looking at the summary and looking for the `Artifact` where the number will be clickable.

![image](https://user-images.githubusercontent.com/234642/162887862-b2a014ee-1da8-4e19-bc4c-29cba39241d9.png)

The link will be `https://github.com/<user>/<repo>/actions/<run_id>` where you can grab that `run_id` and put in manually in your workflow yaml for the `action-download-artifact` step.
