### ISSUE TITLE
Document which parameters will require pagination to avoid rate limiting

### ISSUE THREAD

**Issue by sidx1024** [dawidd6/action-download-artifact#164]
We've seen quite a few times that we're rate limited by GitHub due to multiple API calls. This happens in cases where we have to paginate across results for `listWorkflowRuns` request.

**Example**

Usage A.
```yml
  workflow: 'my-workflow.yml'
  workflow_conclusion: success
  commit: ${{ github.event.pull_request.base.sha }}
```

Usage B.
```yml
  workflow: 'my-workflow.yml'
  workflow_conclusion: success
  branch: ${{ github.event.pull_request.base.ref }}
```

Here, the usage B will be more efficient as branch is an accepted parameter for `listWorkflowRuns` request.
