### ISSUE TITLE
run_id not taken into account

### ISSUE THREAD

**Issue by rknj** [dawidd6/action-download-artifact#181]
Hello.

I'm trying to use your action as it perfectly match my needs but I'm not able to make it work...
Here's the step I wrote. Note that I need to pass `run_id` and `run_number` as I need to get an artifact from a specified run:
```
   - name: Get installer from Org/myRepo
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{ inputs.github_token }}
        workflow: workflow-generating-the-artifact-I-need.yml
        run_id: ${{ inputs.run_id }}
        run_number: ${{ inputs.run_number }}
        path: /tmp/installers/
        repo: Org/myRepo
```

In the logs I get this:
```
Run dawidd6/action-download-artifact@v2
  with:
    github_token: ***
    workflow: workflow-generating-the-artifact-I-need.yml
    run_id: 7504380515
    run_number: 14
    path: /tmp/installers/
    repo: Org/myRepo
    workflow_conclusion: success
```

and output is:
```
==> Artifact name: 
==> Local path: /tmp/installers/
==> Workflow name: workflow-generating-the-artifact-I-need.yml
==> Repository: Org/myRepo
==> Workflow conclusion: success
==> Run number: 14

Error: Not Found
```

I'm guessing that `run_id` is not used which explains why I get a "Not Found" error at the end...
