### ISSUE TITLE
Does this action download the artifacts to a local directory on my device? Or am I missing something.

### ISSUE THREAD

**Issue by ATPAustinPeng** [dawidd6/action-download-artifact#183]
```
name: Compile and Deploy
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Set up Git Repo
              uses: actions/checkout@v2
            - name: Compile LaTeX Document
              uses: xu-cheng/latex-action@v2
              with:
                  root_file: resume.tex
                  latexmk_shell_escape: true
            - name: Upload artifact
              uses: actions/upload-artifact@v2
              with:
                  name: resume
                  path: resume.pdf
    deploy_hash:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download PDF
              uses: actions/download-artifact@v2
              with:
                  name: resume
            - name: Download PDF from action
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: compile.yml
    deploy_main:
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/master'
        steps:
            - name: Download PDF
              uses: actions/download-artifact@v2
              with:
                  name: resume
            - name: Download PDF from action
              uses: dawidd6/action-download-artifact@v2
              with:
                  workflow: compile.yml
```
I'm just trying to get the artifact to compile a LaTeX file, download it to my local device, and then push it back into my repo.
