### ISSUE TITLE
Is it possible to look for and download  specific artifact? 

### ISSUE THREAD

**Issue by vitalyk-multinarity** [dawidd6/action-download-artifact#212]
Hi,
I need to download the specific artifact from a  flow. This flow builds artifacts for a few platforms - like Android, Linux, Windows; and I need to download Android. Is there a way to download the latest Android artifact from the master branch, even if the latest build doesn't have Android artifact (only Windows one for example)?
I tried this code

```
  -    uses: dawidd6/action-download-artifact@v2
        with: 
          workflow_conclusion: success
          repo: mycompany/myrepo
          workflow: myflow.yml
          branch: master
          name: Android  
``` 

but it fails with 

```
==> (not found) Artifact: Android
==> Found the following artifacts instead:
	==> (found) Artifact: Windows 
Error: no artifacts found
```

Thank you,
Vitaly
