### ISSUE TITLE
Allow specifying commit and branch in the same field

### ISSUE THREAD

**Issue by mstorsjo** [dawidd6/action-download-artifact#242]
When integrating with other github actions, many allow specifying either a branch name or a commit id in the same field, such as the `ref` field in https://github.com/actions/checkout. It would be convenient if `action-download-artifact` also would allow intermixing commits and branch names in this way - either by adding a new field `ref` which takes either, or allowing passing a branch name in the `commit` field.

**Comment by mstorsjo** [comment]
As a concrete example, my workflow might look like this:
```
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit to extract from'
        type: string
      branch:
        description: 'Branch to extract from'
        type: string

jobs:
  do-things:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          commit: ${{inputs.commit}}
          branch: ${{inputs.branch}}
          event: push
      - uses: actions/checkout@v3
        with:
          ref: ${{ (inputs.commit != '' && inputs.commit) || inputs.branch }}
          path: repo
```

If there would be only one single field to pass to `action-download-artifact`, it would make the use with other actions such as `actions/checkout` more convenient.
