### ISSUE TITLE
Download artifacts for tag

### ISSUE THREAD

**Issue by jvyden** [dawidd6/action-download-artifact#245]
We have two workflows, one for building and one for releasing built artifacts upon a tag release. They're both summoned from one `push` event, and the release job waits for the other job:

```yml
      - name: Wait for builds
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build, Test, and Upload Builds'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Download artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: main
          workflow: dotnet.yml
          workflow_conclusion: success
          if_no_artifact_found: fail
          skip_unpack: true
```

For some reason, downloading the artifact downloads one from a previous push to master instead of downloading from the job we just waited for. I suspect this is because the commit SHAs match. It would be nice if I could specify the tag, so this workflow only considers workflows for that tag.

P.S: Sorry if this issue doesn't make sense, I'm tired :upside_down_face:
