### ISSUE TITLE
Workflow Run Referenced an Incorrect Artifact

### ISSUE THREAD

**Issue by robronayne** [dawidd6/action-download-artifact#265]
I am using this GitHub Action in one of my workflows in order to retrieve and execute SQL scripts that were created during a previous job. However, I noticed that in one scenario of using this action, it retrieved the wrong GitHub artifact.

With the parameters that I used in my workflow, the action should only retrieve the artifacts that are associated with the current PR.
```
- name: Download Resource Deployment Scripts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
          name: sql-script
          check_artifacts: false
          if_no_artifact_found: fail
```

However, during one of its runs on PR #941 it appears to have retrieved an artifact that was associated with PR #956.

This is the workflow run from PR #941 that retrieved the incorrect artifact. The artifact it retrieved was `1057981208`.

<img width="1689" alt="Screenshot 2023-12-26 at 3 23 38 PM" src="https://github.com/dawidd6/action-download-artifact/assets/78000645/dd8206c1-b6e7-4422-a328-200948ea2c0b">

This is the artifact where it originally appears, as attached to a workflow related to a separate PR.

<img width="1726" alt="Screenshot 2023-12-26 at 3 22 24 PM" src="https://github.com/dawidd6/action-download-artifact/assets/78000645/cb0e4f93-ed2b-42d5-8a04-334f7c12cc62">

I will also be reaching out to GitHub directly to see if there is any more information that I can relay back to you.
