### ISSUE TITLE
Unable to get artifacts from other workflows/runs

### ISSUE THREAD

**Issue by dbudwin** [dawidd6/action-download-artifact#279]
## What I'm Trying To Do

I generate code coverage files to report to SonarCloud.  I save these files as an artifact using `actions/upload-artifact@v4` after running Jest.  I was able to use `actions/download-artifact@v4` to fetch this artifact for `pull_request` events, but this doesn't work for `push` events (like when I merge a PR).  During `push` events only the `sonarCloud.yml` workflow runs and I want it to retrieve the artifacts from the last time Jest ran and produced an artifact.  I don't want to re-run all my Jest tests when I merge a PR.  This is why I decided to try and use this action and give it the PR number associated with a commit.  I am able to get the PR number just fine according to the logs.

### Expected Behavior

I cannot get either of the following scenarios to work using `action-download-artifact`.

#### Scenario 1: Opening a PR

1. A PR is opened
2. A Jest workflow `jest.yml` produces an artifact with code coverage results
3. A SonarCloud workflow `sonarCloud.yml` retrieves this artifact from step 2 and sends it to SonarCloud

#### Scenario 2: Merging a PR

1. A PR is merged
2. A SonarCloud workflow `sonarCloud.yml` is triggered
3. The SonarCloud workflow looks for the code coverage artifact created by the PR associated with the merge commit

## The Issue I'm Having

I get the following warning trying to fetch artifacts from a previous workflow by PR number.  The PR number `4532` is correct, the SHA `a38b9b1c9095431107a3add60da4a5b9dbab63ce` is correct, and the artifact name `code-coverage-reports` is correct:

```
Run dawidd6/action-download-artifact@v2
  with:
    github_token: ***
    workflow: build.yml
    pr: 4532
    name: code-coverage-reports
    search_artifacts: true
    if_no_artifact_found: warn
    workflow_conclusion: success
    repo: [redacted]/[redacted]
    name_is_regexp: false
    path: ./
    allow_forks: true
    check_artifacts: false
    skip_unpack: false
  env:
    COMMIT_SHA: a38b9b1c9095431107a3add60da4a5b9dbab63ce
==> Repository: [redacted]/[redacted]
==> Artifact name: code-coverage-reports
==> Local path: ./
==> Workflow name: build.yml
==> Workflow conclusion: success
==> PR: 4532
==> Commit: a38b9b1c9095431107a3add60da4a5b9dbab63ce
==> Allow forks: true
Warning: no matching workflow run found with any artifacts?
```

## The GitHub Actions YML

I'm using this action like so in `sonarCloud.yml`:

```yml
name: Sonar Cloud

on:
  push:
    branches:
      - staging
      - prod
  workflow_call:

env:
  # The SHA doesn't come from an intuitive place for push events: https://github.com/orgs/community/discussions/25191
  COMMIT_SHA: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}

jobs:
  getPrNumber:
    name: Get PR Number
    runs-on: ubuntu-latest
    outputs:
      prNumber: ${{ steps.get_pr_number.outputs.prNumber }}
    steps:
      - name: Get PR Number Associated With Commit
        id: get_pr_number
        run: |
          prNumber=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/[redacted]/[redacted]/commits/$COMMIT_SHA/pulls | jq -r '.[0].number');
            echo "prNumber=${prNumber}" >> "$GITHUB_OUTPUT"
      - name: setup env variable
        run: echo "PR Number for SHA '$COMMIT_SHA' is '$prNumber'"
        env:
          PR_NUMBER: ${{ steps.get_pr_number.outputs.prNumber }}
  sonarcloud:
    needs: getPrNumber
    name: Sonar Cloud
    runs-on: ubuntu-latest
    steps:
      - name: setup env variable
        run: echo "🚀🚀🚀 env variable is ${{ needs.getPrNumber.outputs.prNumber }}"
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Fetch Archive of Code Coverage Results
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: build.yml
          pr: ${{ needs.getPrNumber.outputs.prNumber }}
          name: 'code-coverage-reports'
          search_artifacts: true
          if_no_artifact_found: warn # temporary until this works
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

### When Opening a PR
![Screenshot 2024-02-28 at 16 06 20](https://github.com/dawidd6/action-download-artifact/assets/15161181/7dd8a31b-69f1-4da1-9ac1-024875b9ee2c)

### When Merging a PR
![image](https://github.com/dawidd6/action-download-artifact/assets/15161181/d02c0e64-7bfc-4aed-9553-aeec946efd65)

## What I've Tried

I've tried all sorts of things with tweaking the params without luck.  I've spent some time studying the code, and it appears for whatever reason it can't find the `runID`.

1. Giving various names for the `workflow` param, from the name of the "parent" workflow `build.yml`, to the name of the workflow file used that generates the artifact `jest.yml`
4. Omitting the `workflow` param completely
5. Using `commit` instead of `pr`
6. Setting `search_artifacts` to `true`
7. Not providing `name` at all so it would return all artifacts

**Comment by dawidd6** [comment]
Please try:

```yml
      - name: Fetch Archive of Code Coverage Results
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: jest.yml
          pr: ${{ needs.getPrNumber.outputs.prNumber }}
          name: code-coverage-reports
```

If that won't work, try:

```yml
      - name: Fetch Archive of Code Coverage Results
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow_search: true
          pr: ${{ needs.getPrNumber.outputs.prNumber }}
          name: code-coverage-reports
```
