### ISSUE TITLE
Artifact created in the same workflow not found

### ISSUE THREAD

**Issue by garysassano** [dawidd6/action-download-artifact#316]
![image](https://github.com/user-attachments/assets/0b2b4e70-e95c-44fc-92ec-bdda2d5f8e72)

![image](https://github.com/user-attachments/assets/80c55243-15c6-4fdb-b43e-75df4f990d56)

**Comment by dawidd6** [comment]
Can't help if you don't show us your workflows.

**Comment by garysassano** [comment]
These are the main steps:

```yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find current PR
        uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: all

      - name: Download workers artifact from merged PR
        uses: dawidd6/action-download-artifact@v6
        with:
          name: cloudflare-workers-${{ env.PR_NUMBER || 'manual' }}
          path: worker/dist/
        env:
          PR_NUMBER: ${{ steps.find_pr.outputs.pr }}
```

**Comment by garysassano** [comment]
These are the main steps:

```yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Find merged PR
        uses: jwalton/gh-find-current-pr@master
        id: find_pr
        with:
          state: close

      - name: Download workers artifact from merged PR
        uses: dawidd6/action-download-artifact@v6
        with:
          name: cloudflare-workers-${{ env.PR_NUMBER || 'manual' }}
          path: worker/dist/
        env:
          PR_NUMBER: ${{ steps.find_pr.outputs.pr }}
```
