### ISSUE TITLE
Repo Not Found

### ISSUE THREAD

**Issue by rogerprz** [dawidd6/action-download-artifact#36]
I may be missing some type of setup but in my workflow, I am getting `Error: Not Found`
Error:
```
Run dawidd6/action-download-artifact@v2
  with:
    workflow: ./test.yaml
    workflow_conclusion: success
    path: cagedstyle-raven
    repo: rogerprz/WorkflowTest2
    github_token: ***
==> Repo: rogerprz/WorkflowTest2
Error: Not Found
```
[Repo Link](https://github.com/rogerprz/WorkflowTesting/blob/main/.github/workflows/download-workflow-artifact.yaml)
```yaml
name: Download Workflow Artifact

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: windows-latest  # For a list of available runner types, refer to

    steps:
    - name: Download Workflow Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Required, workflow file name or ID
        workflow: ./test.yaml # project name

        # SELECTOR
        # Optional, the conclusion of a completed workflow to search for
        # Can be one of:
        # "failure", "success", "neutral", "cancelled", "skipped", "timed_out", "action_required"
        # Ignores conclusion by default (thus using the most recent completed run when no other option is specified, regardless of conclusion)
        workflow_conclusion: success

        # Error: don't specify `run_id`, `branch`, `pr`, `commit` and `workflow_conclusion` together
        # RESEARCH        
        # pr: ${{github.event.pull_request.number}} # Optional, will get head commit SHA
        # commit: ${{github.event.pull_request.head.sha}} # Optional, no need to specify if PR is
        # branch: master # Optional, will use the branch
        # run_id: 1122334455 # Optional, will use specified workflow run

        # RESEARCH
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
#         name: artifact_name

        # TARGET DIRECTORY || nil
        # Optional, directory where to extract artifact
        path: cagedstyle-raven
        repo: rogerprz/WorkflowTest2
```
