### ISSUE TITLE
Empty RunID NotFound (since yesterday)

### ISSUE THREAD

**Issue by yss14** [dawidd6/action-download-artifact#57]
This action worked like a charm for months now on our repos, but since the [big github actions outage yesterday](https://www.githubstatus.com/incidents/xn0sd2x4nd7f) it fails on every build for us.

![Screenshot 2021-03-02 at 08 35 12](https://user-images.githubusercontent.com/4346842/109613986-3acc9780-7b32-11eb-9127-942e7c070b15.png)

```yaml
- name: Download Artifact
   uses: dawidd6/action-download-artifact@v2
   with:
       workflow: ci.build.yaml
       commit: ${{ steps.vars.outputs.commit_hash }}
       name: worknow_backend
```

Seems like the action is not able to resolve the `RunID` of the latest build workflow, which worked like it should before yesterday.
Anyone else experiences this issue?

**Comment by torbjornvatn** [comment]
@yss14 I think it's related to this https://github.community/t/bug-github-api-list-workflow-runs-returns-0-runs-even-though-there-are-runs/165080/3

The github API doesn't return what it's supposed to return

**Comment by yss14** [comment]
@torbjornvatn Thanks for that hint! So I think we have to wait for a fix from GitHub, right?

**Comment by torbjornvatn** [comment]
Yes, I've reported it to them directly as well

**Comment by shaunkingpww** [comment]
I seem to have the same issue with our deployment pipeline. Is there any further information on when the fix will be in place?

**Comment by daniil-shumko** [comment]
This is still not resolved for me. I am trying to get an artefact from the latest(yesterdays) successful run on a specific branch but it downloads an artifact from an older successful run that was made last week. Let's hope they will resolve it soon.

**Comment by kdgs** [comment]
Instead of using the workflow or commit, you can send the run_id with the dispatch event and use it on the action. It solved the issue for me...

On the dispatch event I added: 
`"run_id": "${{ github.run_id }}`

And on the action Im using it like this:

```
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: master.yml
          name: master-workflow-artifact-zip
          repo: ${{github.repository}}
          path: ./dist
          run_id: ${{github.event.client_payload.run_id}}
```
Give it a try...
