### ISSUE TITLE
Failed to generate URL to download artifact

### ISSUE THREAD

**Issue by mohanarpit** [dawidd6/action-download-artifact#58]
I was developing my Github Actions workflow & since yesterday I have been seeing the error: "Failed to generate URL to download artifact"  (screenshot attached).

<img width="683" alt="Screenshot 2021-03-02 at 5 08 03 PM" src="https://user-images.githubusercontent.com/458946/109643180-e2b98380-7b79-11eb-9066-498605815fae.png">

My workflow steps for this action are:

```
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: workflow-package
          path: workflow-package/
```

Seems like I'm missing something basic. Am I doing something wrong or is this a legitimate issue?
