### ISSUE TITLE
[Proposal] Add support for specifying branch and run_id/run_number together

### ISSUE THREAD

**Issue by daniil-shumko** [dawidd6/action-download-artifact#59]
An example scenario will be if I want to download an artifact using the `run_id` or `run_number` that have run against the `branch` specified.

```
with:
  workflow: workflow.yaml
  branch: master
  run_number: ${{ github.event.inputs.run_number }}
```

If the specified `run_number` or `run_id` have not run on the `branch` that was provided an error message should be printed e.g `The run_id/run_number do not match the branch specified`

Feel free to drop your $0.02 in the comments 😄
