### ISSUE TITLE
download an artefact from other repo

### ISSUE THREAD

**Issue by poborin** [dawidd6/action-download-artifact#6]
I'm having a problem with downloading an artifact from another repo by SHA.

this is the code that doesn't work for me:

```yml
    - name: Download upstream PointSDK
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: artifact_workflow.yml
        commit: ${{ github.event.client_payload.sha }} # sha to an upstream event from the web-hook
        name: PointSDK
        path: ./Pods/BluedotPointSDK/PointSDK/
        repo: Bluedot-Innovation/point_sdk_ios
```
It returns

> ==> Commit: fcbc4eeda46737f2fc1234ec871142c705b9b24a
> ##[error]Not Found

however, following commands are working as expected:

```
curl -sL -u UN:PAT https://api.github.com/repos/Bluedot-Innovation/point_sdk_ios/actions/workflows/artifact_workflow.yml/runs | jq -r '.workflow_runs[0].id?'

curl -sL -u UN:PAT https://api.github.com/repos/Bluedot-Innovation/point_sdk_ios/actions/runs/67128363/artifacts

curl -sL -u UN:PAT https://api.github.com/repos/Bluedot-Innovation/point_sdk_ios/actions/artifacts/3637242/zip -o ~/tmp/PointSDK.zip 
```

Would it be possible, to add another parameter to an action? Something like `workflow_run_id`? I'm using it to start a new downstream build without pushing an artifact to a dependency manager. So, an alpha or beta SDK can be integrated into another project.
