### ISSUE TITLE
Unexpected input(s) 'run_number'

### ISSUE THREAD

**Issue by daniil-shumko** [dawidd6/action-download-artifact#60]
I get the following warning when passing the `run_number` to the action as specified in the documentation.
<img width="1296" alt="Screenshot 2021-03-02 at 18 46 37" src="https://user-images.githubusercontent.com/7705571/109698881-ca506580-7b87-11eb-9300-d04846a5f265.png">

Example code:
```
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: workflow.yaml
          run_number: 111
          name: ios_app
```
