### ISSUE TITLE
Allow fetching assets from a branch by event (e.g., commit/push vs. pull-request, ...)

### ISSUE THREAD

**Issue by christian-kreuzberger-dtx** [dawidd6/action-download-artifact#68]
In our workflow we use this action to download artifacts for an integration test for a specific branch.
```
      - name: Download artifact from specified branch
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: CI.yml
          workflow_conclusion: success
          branch: ${{ steps.determine_branch.outputs.BRANCH}}
          path: ./dist
```

![image](https://user-images.githubusercontent.com/56065213/115738531-6d09b100-a38d-11eb-92b3-8532f0abea04.png)

Unfortunately, we often end up getting artifacts from a Pull Request onto that branch, instead of the specified branch.
![image](https://user-images.githubusercontent.com/56065213/115736944-fddf8d00-a38b-11eb-9dc2-2b39af3dbc48.png)

The cause of this is GitHubs API.

However, the fix should be simple. It should be possible to also add an event filter here (e.g., event=push).
https://github.com/dawidd6/action-download-artifact/blob/ca08e8182b250b700fef032325a2fea453220b9f/main.js#L59-L66

See [GitHub API Docs for /runs](https://docs.github.com/en/rest/reference/actions#list-workflow-runs-for-a-repository).

This would also need to be defined as an input in https://github.com/dawidd6/action-download-artifact/blob/master/action.yml 

For comparison:
https://github.com/keptn/keptn/actions/workflows/CI.yml?query=branch%3Arelease-0.8.2+is%3Asuccess
vs.
https://github.com/keptn/keptn/actions/workflows/CI.yml?query=branch%3Arelease-0.8.2+is%3Asuccess+event%3Apush
