### ISSUE TITLE
How to debug "Not Found" error

### ISSUE THREAD

**Issue by BevanR** [dawidd6/action-download-artifact#72]
I have configured this workflow like so;

```
      - name: Download the-web server
        uses: dawidd6/action-download-artifact@v2
        with:
          repo: stqry/the-web
          workflow: the-web.yaml
          branch: develop
          github_token: ${{secrets.GITHUB_TOKEN}}
```

And I get a simple error "Error: Not Found" in GHA:

![image](https://user-images.githubusercontent.com/325176/117245873-afec7e00-ae8f-11eb-9072-1f8d34435cee.png)

1. How do I debug this further?
1. What is required to access an artifact in a private repo within the same organization?
1. Should the `github_token` setting be for the other repo?
