### ISSUE TITLE
Support github.event.workflow_run.*

### ISSUE THREAD

**Issue by major0** [dawidd6/action-download-artifact#79]
It seems to me that this action would have a natural fit if it was in a workflow that was triggered from another workflow.

Origin Workflow:
```
name: Test
on: [pull_request]
jobs:
  DoStuff:
    ---
```

Reporting workflow:
```
name: Reports
on:
  workflow_run:
    workflows:
      - Test
    types:
      - completed

jobs:
  Report:
    steps:
      uses: dawidd6/action-download-artifact@v2
```

The `github.event.workflow_run` context will contain the information about the completed `Test` workflow. It seems like it would be a more natural approach to leverage the Workflow Syntax to orchestrate this action as opposed to attempting to parameterize it.

See: <https://docs.github.com/en/actions/reference/events-that-trigger-workflows#workflow_run>

**Comment by dawidd6** [comment]
Umm. I don't know what do you want me to do here. You are free to make use of any context variable and pass it to action inputs. What else here can be done?

**Comment by JamesMGreene** [comment]
> What else here can be done?

I'm guessing @major0 was maybe hoping you could default some of the inputs (`workflow` and `run_id`) if you detected the current workflow run was triggered by `workflow_run`. 🤷🏻‍♂️ 

Anyway, that would be _nice_ but it's not a big deal to just do it yourself. Here's how I am using it:

```yaml
      - name: Download artifact
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: pr_build
          path: ./
```
