### ISSUE TITLE
"Uri expired" failed workflow

### ISSUE THREAD

**Issue by IvanVnucec** [dawidd6/action-download-artifact#81]
My workflow run failed with the message: 
```
Run dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
  with:
    workflow: main.yml
    name: exec_timetable
    path: ./.
    github_token: ***
    workflow_conclusion: completed,success
    repo: IvanVnucec/rain_alert
==> Workflow: main.yml
==> Repo: IvanVnucec/rain_alert
==> Conclusion: completed,success
==> RunID: 939756615
==> Artifact: 67837064
==> Downloading: exec_timetable.zip (56 B)
Error: {"count":11,"value":"Uri expired"}
```

Here is the link of the run https://github.com/IvanVnucec/rain_alert/actions/runs/939884480. I hope you can see it.

I've also checked the previous workflow and there were uploaded artifacts that I could download.

**Comment by dawidd6** [comment]
https://docs.github.com/en/rest/reference/actions#download-an-artifact

> Gets a redirect URL to download an archive for a repository. This URL expires after 1 minute.

**Comment by IvanVnucec** [comment]
Can you provide me with more details how is this URL connected with the action-download-artifact?

**Comment by dawidd6** [comment]
https://github.com/dawidd6/action-download-artifact/blob/702aa78447730912df2847a019bba79adb478aa4/main.js#L113

**Comment by IvanVnucec** [comment]
Is there any fix for this?

**Comment by dawidd6** [comment]
Can't do anything about it. Looks like some random GitHub API hiccup to me.

**Comment by IvanVnucec** [comment]
I've added another step to try again if the first download try had failed. It's not tested yet if this fixes the issue because I don't know how to recreate the URL timeout above.
```
- name: Try again to download execution timetable from the last workflow
        if: ${{ always() && steps.download_exec_timetable.outcome == 'failure' }}
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: main.yml
          name: exec_timetable
          path: ./.
```

PS: I'll leave the Issue opened for some future fix.
