### ISSUE TITLE
Missing something basic?

### ISSUE THREAD

**Issue by lgadalla-impinj** [dawidd6/action-download-artifact#83]
Trying to use this action to demo passing artifacts between workflows, and not having much luck. "Stage1" workflow generates artifact and triggers "Stage2" workflow:

```
name: Stage1

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Runs a set of commands using the runners shell
      - name: Generate a synthetic artifact
        run: |
          ./stage1.sh 10000

      # Save the build artifact(s)
      - name: Save artifact for downstream pipeline
        uses: actions/upload-artifact@v2
        with:
          name: stage1-artifacts
          path: "**/*.art"
          if-no-files-found: error

      # Trigger the next stage of the pipeline
      - name: Trigger the stage2 workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DEMO_ACCESS_TOKEN }}
          repository: myorg/stage2
          event-type: stage1-build
          client-payload: '{"repo": "${{ github.repository }}", "workflow": "${{ github.workflow }}", "run_id": "${{ github.run_id }}", "ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
```

"Stage2" workflow attempts to get the artifact, but always fails:

```
name: Stage2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  repository_dispatch:
    types: [stage1-build]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2.3.4

      # Say the event client data
      - name: Show client payload context
        env:
          CLIENT_PAYLOAD_CONTEXT: ${{ toJSON(github.event.client_payload) }}
        run: echo "$CLIENT_PAYLOAD_CONTEXT"

      # Get the artifacts from upstream
      - name: Get upstream pipeline artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          run_id: "${{ github.event.client_payload.run_id }}"
          workflow: "${{ github.event.client_payload.workflow }}"
          repo: "${{ github.event.client_payload.repo }}"
```

Results from the triggered "Stage2" workflow always look like this, after many different permutations of args to the action-download-artifact action:

```
Run echo "$CLIENT_PAYLOAD_CONTEXT"
{
  "ref": "refs/heads/main",
  "repo": "myorg/stage1",
  "run_id": "965258430",
  "sha": "7b6f14dc363158c7370c9549130a776f48b4fefe",
  "workflow": "Stage1"
}

Run dawidd6/action-download-artifact@v2
==> Workflow: Stage1
==> Repo: myorg/stage1
==> Conclusion: completed,success
==> RunID: 965258430
Error: Not Found
```

Am I missing something really basic here?
