### ISSUE TITLE
Support for wildcard names

### ISSUE THREAD

**Issue by TinaTiel** [dawidd6/action-download-artifact#85]
Super useful GH action, thank you for providing this to the community!
I'm wondering if supporting wildcards in names would be an useful feature?

For example, in [cases like this](https://github.com/Palakis/obs-websocket/runs/2879789876?check_suite_focus=true) with many different platforms I'd like to download just the Ubuntu64 artifacts. For example:
```
- name: Download Palakis latest Ubuntu Build
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: main.yml # "CI Multiplatform Build"
        branch: master
        repo: Palakis/obs-websocket
        name: obs-websocket*amd64.deb
        path: downloads
```

If this sounds like a great idea, I could try contributing this feature (or let me know if you'll do it instead).
