### ISSUE TITLE
Action suddenly stopped working

### ISSUE THREAD

**Issue by deep-mm** [dawidd6/action-download-artifact#93]
![image](https://user-images.githubusercontent.com/29853549/128015380-9717b0f6-ab57-44c5-abd4-a83726446d6c.png)

This was working fine before today, but today unfortunately I am getting this error that Run ID not found.
For my other repository it takes the artifacts of previous runs, but doesn't identify new runs of the workflow

**Comment by tehKapa** [comment]
I have the same issue. I can't download artifacts from another repository. 2 hours ago, it worked.

In my pipeline, I've got the error "no artifacts found".

**Comment by yss14** [comment]
Same issue here...

**Comment by dawidd6** [comment]
Either something in GitHub changed or broke. I didn't make any changes recently.

**Comment by AntonyKing7D** [comment]
Same here:
![Screenshot_20210803_153038](https://user-images.githubusercontent.com/31652450/128035704-141a1db2-6d09-422d-b971-266ee5ebcdd5.png)

**Comment by danjamesmay** [comment]
> This was working fine before today, but today unfortunately I am getting this error that Run ID not found.
For my other repository it takes the artifacts of previous runs, but doesn't identify new runs of the workflow

We've found this issue as well. We ran the action against a workflow run from 3 months ago and it still works. 

But, any workflows runs we've run since 11:42 BST haven't managed to find the run ID.

**Comment by abelikt** [comment]
Same issue here, on our repositories old run-ids are taken

**Comment by danjamesmay** [comment]
This appears to be the underlying API call that this action calls to get the run ID: https://docs.github.com/en/rest/reference/actions#list-jobs-for-a-workflow-run

Code where it's called: https://github.com/dawidd6/action-download-artifact/blob/master/main.js#L60

I've opened a support ticket with Github to see if they know of an incident with this endpoint and workflow run IDs...

**Comment by vmirkin-proag** [comment]
> I've opened a support ticket with Github to see if they know of an incident with this endpoint and workflow run IDs...

Any word from GitHub?

**Comment by JayyTurakhia** [comment]
This was a very reliable action (still is) until something underneath changed. We are also facing this issue.

**Comment by jamesgmorgan** [comment]
Same issue found i.e. this action just stopped working for runs from today, still works for runs from yesterday.

On doing some debugging, I agree with @danjamesmay i.e. it appears to be a problem with the data returned by `Octokit/listWorkflowRuns()`.  In our case, there's currently a total of 118 runs for the workflow we're querying but listWorkflowRuns() indicates that there's only 115.  However a direct call to the GitHub REST API confirms there's 118, ex:

$ curl -sLH 'Accept: application/vnd.github.v3+json' -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/ORG/REPO/actions/workflows/WORKFLOW/runs | grep total_count
  "total_count": 118,
   
![Screen-Shot-2021-08-04-at-1-10-11-AM](https://user-images.githubusercontent.com/1799173/128126459-96bebf61-88cc-4fcc-8e49-10cd15a474c9.png)

I've also opened a support ticket.

**Comment by 6akcuk** [comment]
Same issue, our deployments stuck now. Is there any alternative way/another action to make it work?

**Comment by danjamesmay** [comment]
Still no reply from Github support yet. I don't have premium support though, just what's bundled with Github Teams.

**Comment by firke** [comment]
Also had the same issue - manually specifying **run_id** did the trick for now.

**Comment by VG-CoE-QA** [comment]
Same Issue here, how to find the correct run_id to supplement it by myself?

**Comment by firke** [comment]
@VG-CoE-QA in the Actions tab go to the action from which you want to get artifacts, go to a specific run, it's in the url: https://github.com/<owner>/<repo>/actions/runs/<id>.
Possibly run_number would work as well, but i've not tested it.

**Comment by mowies** [comment]
I just found out that by providing the `run_id` to the action, it still works.
I used the `curl` from @jamesgmorgan 's [comment](https://github.com/dawidd6/action-download-artifact/issues/93#issuecomment-892373245) and extended it for this purpose like this:
```
- name: Find latest successful run ID
  id: last_run_id
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    REPO_SLUG: "owner/repo"
    BRANCH: "your-branch"
    WORKFLOW: "CI.yml"
  run: |
    RUN_ID=$(curl -sLH 'Accept: application/vnd.github.v3+json' -H "Authorization: token $GITHUB_TOKEN" "api.github.com/repos/$REPO_SLUG/actions/workflows/$WORKFLOW/runs" | jq --arg branch "$BRANCH" -c '[.workflow_runs[] | select( .conclusion == "success" and .head_branch == $branch)][0] | .id')
    echo "::set-output name=RUN_ID::$RUN_ID"
```
